copyright: Copyright (c) Abstract Machines
repo_url: https://github.com/absmach/s0-docs.git
site_description: S0 Documentation
site_name: S0
site_url: ""
edit_uri: ""

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: "#"

nav: 
  - Overview: index.md
  - Features: features.md
  - S0 Start Up: s0-user-description.md
  - Architecture: architecture.md
  - S0 Pinouts: s0-pinouts.md
  - SO Baseboard: s0-baseboard.md
  - Baseboard Startup: baseboard-user-description.md
  - Baseboard Schematics: baseboard-schematics.md
  - Baseboard Pinouts: baseboard-pinouts.md
  - Software:
      - Overview: software-overview.md
      - Getting Started: software-getting-started.md
      - Uploading Code: uploading-code.md
      - Examples: 
          - WiFi: wifi.md
          - MQTT: mqtt.md
          - HTTP: http.md
          - WEBSOCKETS: websockets.md
          - COAP: coap.md
          - COAP-DTLS: coaps.md
          - MQTTS: mqtts.md
          - HTTPS: https.md

